package com.capg.chalo.service;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.capg.chalo.entity.Payment;
import com.capg.chalo.exception.CustomException;
import com.capg.chalo.repository.PaymentRepository;


	
	@SpringBootTest
	@TestMethodOrder(OrderAnnotation.class)
	class PaymentServiceTest {

		@Autowired
		public PaymentRepository paymentRepository;
		@Autowired
		public PaymentService paymentService;
		
		@Test
		@Order(1)
		void testAddPayment() {
			Payment payment = new Payment();
			payment.setAmount(520);
			payment.setPaymentType("gpay");
			paymentRepository.save(payment);
			assertNotNull(paymentRepository.findById(8L).get());
			}
		
		@Test
		@Order(2)
		void testGetPayment() throws CustomException {
			Payment payment = new Payment();
			payment = paymentService.showPaymentById(10L);
			assertNotNull(payment);
		}
		
		@Test
		@Order(2)
		void testGetAllPayments() {
			assertNotNull(paymentService.showAllPayments());
			
		}
		
		@Test
		@Order(4)
		void testUpdatePayment() {
			Payment payment = paymentRepository.findById(11L).get();
			payment.setAmount(360);
			payment.setPaymentType("phonepe");
			paymentRepository.save(payment);
	//	assertNotNull(360, paymentRepository.findById(11L).get().getPaymentId());
		assertNotNull("phonepe", paymentRepository.findById(11L).get().getPaymentType());
		}
//		
//		@Test
//		@Order(5)
//		void testShowPaymentById() {       //autogenerated
//			
//		}
//		

//		@Test
//		@Order(5)
//		void testDeleteByPaymnetId() {
//			paymentRepository.deleteById(452L);
//			assertThat(paymentRepository.existsById(1L)).isFalse();
//		}
		
		@Test
		@Order(6)
		void testDeleteAllPayments() {
			assertNotNull(paymentService.showAllPayments());
		}
		
		

	}
